#!/usr/bin/env bash
# Render the pictures used by README.md into docs/img/.
#
# These PNGs are the only generated files in the repo that are committed:
# everything under versions/ is ignored, so a visitor on GitHub would otherwise
# see a model with no picture of it. They are small and regenerated by
#
#   ./render_docs.sh
#
# The progress gallery is rendered from the .scad copies in versions/ (those are
# tracked), all with one camera, so the frames are comparable.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"
OS=${OPENSCAD:-openscad}
OUT=docs/img
mkdir -p "$OUT"

r() { out=$1; size=$2; shift 2; "$OS" -o "$OUT/$out" --render --imgsize="$size" "$@" ky023_boot.scad >/dev/null; echo "  $out"; }

ISO='--camera=-8,0,4,60,0,35,225'          # whole assembly, three-quarter view

echo "== overview"
r hero.png     1400,1050 $ISO -D 'part="assembly"'
r section.png  1400,1050 --projection=o --camera=-8,0,6,90,0,0,160 -D 'part="assembly_section"'
r seal.png     1000,750  --projection=o --camera=13,0,-1,90,0,0,50 -D 'part="assembly_section"'
r pcb.png       900,700  --projection=o --camera=0,-1,0,0,0,0,115  -D 'part="mock"'

echo "== bellows variants"
r bellows-v019.png 900,900 --projection=o --camera=0,0,12,90,0,0,110 -D 'part="section"'
r bellows-deep.png 900,900 --projection=o --camera=0,0,12,90,0,0,110 -D 'part="section"' -D 'bellows="deep"'

echo "== parts"
r part-boot.png   700,560 --camera=0,0,10,55,0,25,140   -D 'part="boot"'
r part-ring.png   700,560 --camera=0,0,1,55,0,25,95     -D 'part="ring"'
r part-cap.png    700,560 --camera=0,0,16,55,0,25,100   -D 'part="cap"'
r part-box.png    700,560 --camera=-8,0,-8,235,0,25,200 -D 'part="box"'
r part-lid.png    700,560 --camera=-8,0,-17,55,0,25,180 -D 'part="lid"'
r part-gasket.png 700,560 --camera=-8,0,0,55,0,25,180   -D 'part="gasket"'

echo "== mould"
r mould.png 1200,900 --projection=o --camera=0,0,16,90,0,0,180 -D 'part="mould_section"'

# ---- progress gallery ------------------------------------------------------
# One camera for every frame, so the pictures may be compared; the sources come
# from the version folders (only their .scad is tracked, which is enough).
echo "== progress"
for v in v001 v005 v006 v019; do
    d=$(echo versions/$v-*/ | cut -d' ' -f1)
    [[ -f $d/ky023_boot.scad ]] || { echo "  skip $v (no source)"; continue; }
    "$OS" -o "$OUT/progress-$v.png" --render --imgsize=900,700 $ISO \
          -D 'part="assembly"' "$d/ky023_boot.scad" >/dev/null
    echo "  progress-$v.png"
done
r progress-now.png 900,700 $ISO -D 'part="assembly"'

echo "== done"
ls -la "$OUT"
